"use strict";var dataToSend={};var recaptcha_get=false;if(!sessionStorage.getItem('TildaPageAuth')){sessionStorage.setItem('TildaPageAuth','QVJqd0VNQUpTdHRKb2t0b2xvSi80MnYydXlYS0MvYTNMOFBrbTNXbkRmUT0');}
function sendData(){showLoader();$.post('https://auth.tildacdn.com/api/accesspage',dataToSend,function(response){if('error'in response){if(sessionStorage.getItem('TildaPageAuth')){sessionStorage.removeItem('TildaPageAuth');}
window.location.reload(true);}
if(response==''){if(sessionStorage.getItem('TildaPageAuth')){sessionStorage.removeItem('TildaPageAuth');}
window.location.reload(true);}
if(response['status']=='success'){displayContent(response['content']);}else{$("#div_inner_form").show();if($('#page-auth-form').length==0){drawPasswordForm();}
if(response['message']!='session'){showError(response['message']);}
hideLoader();if(recaptcha_get){document.getElementsByTagName('iframe')[0].contentWindow.postMessage('tilda-reset','*');}
$('#page-auth-form input:first').val(response['csrf_val']);}
$('.tilda-input-button').removeAttr('disabled');},'json');}
function drawPasswordForm(){$('body').append('<div class="outer">    <div class="inner" id="div_inner_form" style="z-index: 10; display: none;">        <form id="page-auth-form" action="" method="post">            <input type="hidden" name="csrf" value="Z0xmM2VXU2thZDFjR2V4clNqdGRJeGQxVjZnSEhsc0tTdjhaZTIvcFhXND0">            <table cellpadding="0" cellspacing="0" style="margin-top: -10px;margin-left: -5px;"> </tr>                <tr>                    <td colspan="5" style="text-align: center" id="error-message"></td>                </tr>                <tr>                    <td></td>                    <td class="td1">                        <svg width="20" height="26" xmlns="http://www.w3.org/2000/svg">                            <g opacity=".9" fill="none">                                <path fill="#000" d="M0 11.7h20V26H0z"/>                                <path d="M1.844 14V8.769C1.844 4.479 5.432 1 9.858 1c4.426 0 8.014 3.478 8.014 7.769V14"                                      stroke="#000"/>                            </g>                        </svg>                    </td>                    <td class="td2"><input class="tilda-input-text" type="password" placeholder="Password"></td>                    <td class="td3">                        <button class="tilda-input-button" disabled="disabled">                            <svg class="tilda-arrow" width="36" height="24" xmlns="http://www.w3.org/2000/svg">                                <path d="M0 12h30m1 .35L19.508.27M31 11.662L19.508 22.73" fill="none"/>                            </svg>                        </button>                    </td>                </tr>            </table>        </form>    </div></div>');$('body').append('<iframe id="iframe_recaptcha" width="320px" height="500px" style="position: absolute; bottom: 10px; right: 10px; border: none;" src="https://auth.tildacdn.com/api/recaptcha"></iframe>');$('.tilda-input-button').removeAttr('disabled');$('.tilda-input-text').focus();}
window.addEventListener("message",receiveMessage,false);function receiveMessage(event){try{if(event.data!=''&&event.data.indexOf('tilda-')!=-1){dataToSend['g-recaptcha-response']=event.data.substr(6);recaptcha_get=true;sendData();}}catch(e){}}
function displayContent(content){document.open();document.write(content);document.close();}
function getFormData(){dataToSend.password=$('.tilda-input-text').val();dataToSend.projectid=$('#allrecords').attr('data-tilda-project-id');dataToSend.pageid=$('#allrecords').attr('data-tilda-page-id');dataToSend.csrf=$('#page-auth-form input:first').val();dataToSend.session=sessionStorage.getItem('TildaPageAuth');}
function showError(error){$('#error-message').html(error);$('#error-message').show();$('.tilda-input-button').removeAttr('disabled');$('.tilda-input-text').focus();}
function hideError(){$('#error-message').hide();$('#error-message').text('');}
function showLoader(){$('.td3 button svg').hide();$('.td3 button').addClass('t-btn_sending');document.getElementById('iframe_recaptcha').style.zIndex=100;}
function hideLoader(){$('.td3 button').removeClass('t-btn_sending');$('.td3 button svg').show();document.getElementById('iframe_recaptcha').style.zIndex=0;}
$(document).ready(function(){$('head').append('<style>\n'+'#error-message{font-size: 10pt; max-width: 310px;}'+'.t-btn_sending{color:transparent!important;opacity:1;position:relative}.t-btn_sending:before{content:\'\';box-sizing:border-box;position:absolute;/*top:50%;left:50%;*/width:30px;height:30px;margin-top:-15px;margin-left:-15px;border-radius:50%;border:2px solid #ccc;border-top-color:#333;animation:t-submit-spinner .6s linear infinite}@keyframes t-submit-spinner{to{transform:rotate(360deg)}}'+'html,body{height:100%;margin:0;padding:0;background-color:#f3f3f3}.outer{display:flex;width:100%;height:100%}.inner{margin:auto; padding: 0; max-width: 330px!important;}.tilda-input-text{height:58px;width:100%;border:0;background-color:inherit;font-size:11pt;font-family:\'tfutura\',Arial,sans-serif}:focus{outline:none}table tr{height:60px;font-family:\'tfutura\',Arial,sans-serif}.tilda-input-button{border:0;height:60px;width:100%;margin:0;padding:0;background-color:inherit;cursor:pointer;color:#fff;transition: background-color 700ms ease-out;}.tilda-input-button:hover{background-color:#000;}.tilda-input-button:hover .tilda-arrow{stroke: #FFF;}.tilda-input-button:disabled{background-color:#F3F3F3;}.tilda-arrow{margin-left:20px;margin-right:15px;stroke: #000;}.tilda-arrow:hover{stroke: #FFF}.td1{border:1px solid #000;border-right:0;padding-left:15px;padding-right:20px}.td2{border-top:1px solid #000;border-bottom:1px solid #000;padding:0; width: 60%}.td3{border:1px solid #000;padding:0;vertical-align:middle;width: 73px; font-size: 0;}');drawPasswordForm();getFormData();sendData();$('body').on('submit','#page-auth-form',function(e){e.preventDefault();e.stopPropagation();hideError();$('.tilda-input-button').attr('disabled','disabled');getFormData();if(dataToSend.password==''){showError('Enter password');return false;}
showLoader();document.getElementsByTagName('iframe')[0].contentWindow.postMessage('tilda-execute','*');return;});});